### ISSUE TITLE
Extra quotes around 

### ISSUE THREAD

**Issue by paulkotz** [silbinarywolf/silverstripe-components#10]
Attributes such as input type that are passed are rendered with extra quote marks. Example output:

<input class="FormTextInput__input Text"  type=&quot;email&quot; name=&quot;Email&quot; class=&quot;email text&quot; id=&quot;Symbiote_ComponentListing_FormKitchensink_Form_Email&quot; placeholder=&quot;name@domain.com&quot; />

Which the DOM renders as:

<input class="FormTextInput__input Text" type="&quot;date&quot;" name="&quot;BirthDate&quot;" text&quot;="" id="&quot;Symbiote_ComponentListing_FormKitchensink_Form_BirthDate&quot;" data-isodateformat="&quot;yyyy-MM-dd&quot;" data-jquerydateformat="&quot;yy-mm-dd&quot;">

The code I'm using for a text field is:

<:FormTextInput class="$Attributes.class"
	attributesHTML="$AttributesHTML(class)"
/>

Removing the quotes around $AttributesHTML(class) outputs similar, but the ampersands are rendered as &amp; giving:

<input class="FormTextInput__input Text"  type=&amp;quot;email&amp;quot; name=&amp;quot;Email&amp;quot; class=&amp;quot;email text&amp;quot; id=&amp;quot;Symbiote_ComponentListing_FormKitchensink_Form_Email&amp;quot; placeholder=&amp;quot;name@domain.com&amp;quot; />

**Comment by paulkotz** [comment]
This is happening on the front-end-tooling master branch as well as the form components branch.

**Comment by silbinarywolf** [comment]
This is easy fixed.  I just need to make the template change the output from things like:
`$scope->locally()->XML_val('Title', null, true);`
to:
`$scope->locally()->XML_val('Title', null, false);`

The last parameter stops casting to an Object type. (ie. a php string becomes "Text" object in SS if true)
I'll make sure to add a unit test for this.

**Comment by silbinarywolf** [comment]
@paulkotz This is now fixed with a test to ensure it doesn't come back.
https://github.com/silbinarywolf/silverstripe-components/blob/dev/tests/ComponentTest.php#L141
