### ISSUE TITLE
& in strings passed are escaped as &amp; not good for URLs

### ISSUE THREAD

**Issue by paulkotzsymbiote** [silbinarywolf/silverstripe-components#14]
When passing a link string like:

http://mycoolwebsite/links/getForm?Search=&Sort_By=&Sort_Direction=&start=0

into a component, it renders as

http://mycoolwebsite/links/getForm?Search=&amp;Sort_By=&amp;Sort_Direction=&amp;start=0

Which won't go to the desired page.

**Comment by silbinarywolf** [comment]
@paulkotzsymbiote 
Fixed and in release:
- https://github.com/silbinarywolf/silverstripe-components/releases/tag/1.0.2

This bug should not occur in SilverStripe 4.X but if it happens to be there, we'll need to up-port(?) the test
