### ISSUE TITLE
Template lookup for components

### ISSUE THREAD

**Issue by nyeholt** [silbinarywolf/silverstripe-components#18]
Not sure of the intent with the layout of themes/{mytheme}/templates/components - so this may not be an issue. But, in some examples, you'll have a layout like

![image](https://user-images.githubusercontent.com/161730/42817813-92b7f4ee-8a12-11e8-9e51-a0fdd1a65423.png)

The issue with this being that `ComponentService::renderComponent` only looks in 

```
$templates = [
            ["type" => "components", $name],
            ["type" => "Includes", $name],
            $name
        ];
```
which can't find the template. Changing to 

```
$templates = [
            ["type" => "components", $name],
            ["type" => "components/atoms", $name],
            ["type" => "components/molecules", $name],
            ["type" => "components/organisms", $name],
            ["type" => "Includes", $name],
            $name
        ];
```

works as expected.

**Comment by silbinarywolf** [comment]
@nyeholt You've fixed this with a PR. Also this issue only affects SS4. Closing.
