### ISSUE TITLE
Re-enable Travis integration

### ISSUE THREAD

**Issue by silbinarywolf** [silbinarywolf/silverstripe-components#40]
Looks like automated tests with Travis are no longer online? You might want to re-enable this. There are a lot of tests here that can catch subtle XML escaping issues :)

cc @nyeholt @JoshuaCarter @nglasl

**Comment by nglasl** [comment]
I've now made sure this is re-enabled, can you please confirm if you can see https://travis-ci.org/symbiote/silverstripe-components?

**Comment by silbinarywolf** [comment]
Fixed. Now you just have failing tests!
https://github.com/symbiote/silverstripe-components/issues/42

**Comment by nglasl** [comment]
Thanks for opening a follow up issue :)
